# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=11)),
                ('psd', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('longtitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_in_week', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期天')], max_length=1)),
                ('time_begin', models.TimeField(default=django.utils.timezone.now)),
                ('time_end', models.TimeField(default=django.utils.timezone.now)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.People')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.Place'),
        ),
    ]
