# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time',
        ),
        migrations.AddField(
            model_name='time',
            name='time_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='time',
            name='time_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
