# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='psd',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
