# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_auto_20170719_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePeopleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.People')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.Place')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.Time')),
            ],
        ),
    ]
