# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_auto_20170719_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.AlterField(
            model_name='people',
            name='people_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
