# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_auto_20170719_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='place',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='time',
            name='time_begin',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='time',
            name='time_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
