# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0007_time_day_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='tel_num',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='day_in_week',
            field=models.CharField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期天')], max_length=3),
        ),
    ]
